### ISSUE TITLE
Connection returned HTTP code: 401 with message: Unauthorized

### ISSUE THREAD

**Issue by professional-real** [Azure-Samples/ms-identity-java-daemon#3]
I just run the java daemon console application calling Microsoft Graph using its own identity using MSAL. The program compiled successfully. but while executing, it is showing a 401 error with generated token. So I am unable to figure out what parameter is missing or what setting in-app registration is not correct? I am using:
TENANT_SPECIFIC_AUTHORITY = "https://login.microsoftonline.com/78c1652d-8aa6-4020-99f5-5efc8a61bd70";
CONFIDENTIAL_CLIENT_ID = "<from app registration>";
CONFIDENTIAL_CLIENT_SECRET = "<created client sceret>";
GRAPH_DEFAULT_SCOPE = "https://graph.microsoft.com/.default";
Token generated but after verification, with https://jwt.io/ it is not verified successfully.
So can anyone tell me what is the exact issue to make it correct?

**Comment by sangonzal** [comment]
@professional-real Did you grant admin consent to the application you registered? Step 2.6 in the README.
