### ISSUE TITLE
Why can't get I get ClientCredentialGrant.java to work?

### ISSUE THREAD

**Issue by jayr-davis** [Azure-Samples/ms-identity-java-daemon#4]
I have an existing, fielded app that is using adal4j to get a token.  
So now I am trying to convert to MSAL4j.

So I use an existing (and working) clientId, clientSecret and tenantId and plug them in to the getAccessTokenByClientCredentialGrant() subroutine and I get a Jackson error (see below).

com.microsoft.aad.msal4j.MsalClientException: com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class com.microsoft.aad.msal4j.InstanceDiscoveryMetadataEntry]

I am using
	<groupId>com.fasterxml.jackson.dataformat</groupId>
	<artifactId>jackson-dataformat-cbor</artifactId>
	<version>2.10.3</version>
and msl4j version 1.4.0.

Help! 
[GetTokenUsingMsal4j.java.txt](https://github.com/Azure-Samples/ms-identity-java-daemon/files/4471635/GetTokenUsingMsal4j.java.txt)

**Comment by sangonzal** [comment]
@jayr-davis The sample works for you, but when you add MSAL4J to you application it doesn't?

**Comment by jayr-davis** [comment]
Not exactly.
I am **assuming** that the example is supposed to work but it it is not working for me.

Attached here is my Adal4j-working code; same input params, getting the same token, but this one WORKS.
[GetTokenUsingAdal4j.java.txt](https://github.com/Azure-Samples/ms-identity-java-daemon/files/4476201/GetTokenUsingAdal4j.java.txt)

Note that the ClientId, TokenId, ClientId and TenantId are actually being supplied by a project at Microsoft. :-)

Thanks

**Comment by sangonzal** [comment]
Can you try cloning the sample, and plugging in the TenantId, ClientId, and secret and see if you run into the same error?

**Comment by lyytinen** [comment]
I'm also getting the same exception when trying to authenticate from a Scala notebook in Azure DataBricks 6.4 (Apache Spark 2.4.5, Scala 2.11) and using msal4j 1.4.0. Everything works when I run the same code locally.

**Comment by lyytinen** [comment]
I think this is an issue in the msal4j itself so I opened https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/213.

**Comment by jayr-davis** [comment]
Same problem. (see below)

Now, to be clear, I didn't go "register" anything at any website.
I was given these values and they WORKED with AdaL4j.
(And yes, they were "real" 36 character TenantIds and ClientIds; I just did a clumsy
job of XXX-ing them out for this post.)


SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" Oops! We have an exception of type - class java.util.concurrent.ExecutionException
Exception message - com.microsoft.aad.msal4j.MsalServiceException: AADSTS700016: Application with identifier 'XXXXXXXXXX' was not found in the directory 'XXXXXXXXXXX'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.
Trace ID: ccdf4fa0-317f-4875-83c2-c27e37112900
Correlation ID: 429f3187-d9f4-43a3-8942-00af4274f17e
Timestamp: 2020-04-15 16:57:23Z
java.util.concurrent.ExecutionException: com.microsoft.aad.msal4j.MsalServiceException: AADSTS700016: Application with identifier 'XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX' was not found in the directory 'XXXXXXXXXXXX'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.
Trace ID: ccdf4fa0-317f-4875-83c2-c27e37112900
Correlation ID: 429f3187-d9f4-43a3-8942-00af4274f17e
Timestamp: 2020-04-15 16:57:23Z
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at ClientCredentialGrant.getAccessTokenByClientCredentialGrant(ClientCredentialGrant.java:61)
	at ClientCredentialGrant.main(ClientCredentialGrant.java:32)
Caused by: com.microsoft.aad.msal4j.MsalServiceException: AADSTS700016: Application with identifier 'XXXXXX' was not found in the directory 'XXXXXX'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.
Trace ID: ccdf4fa0-317f-4875-83c2-c27e37112900
Correlation ID: 429f3187-d9f4-43a3-8942-00af4274f17e
Timestamp: 2020-04-15 16:57:23Z
	at com.microsoft.aad.msal4j.MsalServiceExceptionFactory.fromHttpResponse(MsalServiceExceptionFactory.java:43)
	at com.microsoft.aad.msal4j.TokenRequestExecutor.createAuthenticationResultFromOauthHttpResponse(TokenRequestExecutor.java:81)
	at com.microsoft.aad.msal4j.TokenRequestExecutor.executeTokenRequest(TokenRequestExecutor.java:36)
	at com.microsoft.aad.msal4j.ClientApplicationBase.acquireTokenCommon(ClientApplicationBase.java:91)
	at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.execute(AcquireTokenByAuthorizationGrantSupplier.java:52)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:57)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:17)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by sangonzal** [comment]
@jayr-davis this is a different problem. The first problem that you mentioned is related to some dependency that you are bringing in your project which has a dependency on an older version of Jackson, which then MSAL tries to use. Same issue that @lyytinen noted in https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/213. You can either drop the MSAL version to 1.2 which uses Gson or try dropping the version of com.fasterxml.jackson.dataformatjackson-dataformat-cbor to 2.10.1 and see if that fixes the issue.

In regards to the issue that you are now seeing, that is coming from the AAD service. If you are saying that the values for client id and tenant id that you are using work in ADAL, and you are using the same values, not sure why you are running into that specific issue. Do you have access to the app registration in the azure portal?

**Comment by jayr-davis** [comment]
#1:  Thanks, I'll try that

#2:  Not at ALL trying to sound snarky, but these Ids and secrets are being provided to me from a large project by Microsoft.  The project is [FarmBeats](https://www.microsoft.com/en-us/garage/wall-of-fame/farmbeats/).  Should I push back to them and ask them ... what?
If the data is MSAL compatible or v1 vs v2 or ???
I *do* have good contacts inside the project; they will respond if I give them a specific question.

thanks.

**Comment by sangonzal** [comment]
@jayr-davis I just tested with ADAL and it actually returns the same error - so this didn't work with ADAL either. They probably have the wrong values.

**Comment by jayr-davis** [comment]
The system was apparently JUST uninstalled from Azure, which then causes this error.  I just received new credentials.  Let me ensure THOSE work and then I will send them to you (sideways like before).

**Comment by sangonzal** [comment]
Didn't hear back. Feel free to reopen if with any other questions.

**Comment by Kirankawade** [comment]
I could acquire token using  git code:https://github.com/Azure-Samples/ms-identity-java-daemon
But could not access Graph Calendar API's. still you can disable SSL validation using below code.
@Bean
  public Boolean disableSSLValidation() throws KeyManagementException, NoSuchAlgorithmException {
    final SSLContext sslContext = SSLContext.getInstance("TLSv1.2");

      sslContext.init(null, new TrustManager[] { new X509TrustManager() {
      @Override
      public void checkClientTrusted(X509Certificate[] x509Certificates, String s) throws CertificateException {
        LOGGER.info("checkClientTrusted no-op implementation invoked");
      }

      @Override
      public void checkServerTrusted(X509Certificate[] x509Certificates, String s) throws CertificateException {
        LOGGER.info("checkServerTrusted no-op implementation invoked");
      }

      @Override
      public X509Certificate[] getAcceptedIssuers() {
        return new X509Certificate[0];
      }
    } }, null);

    HttpsURLConnection.setDefaultSSLSocketFactory(sslContext.getSocketFactory());
    return true;
  }
