### ISSUE TITLE
Connection returned HTTP code: 403 with message: Forbidden

### ISSUE THREAD

**Issue by shamis** [Azure-Samples/ms-identity-java-daemon#5]
403 error when fetching users (https://graph.microsoft.com/v1.0/users). Access token is fetched successfully.

**Comment by sangonzal** [comment]
@shamis did you follow the registration instructions in the README? especially step 2.5 and 2.6?

**Comment by sangonzal** [comment]
If anyone else runs into this issue in the future, ensure that when you add the Microsoft Graph permissions on the Azure portal, that you click on "Application Permissions" and not "Delegated Permissions"
