### ISSUE TITLE
Failed to run sample in msal-client-credential-secret

### ISSUE THREAD

**Issue by penzyc** [Azure-Samples/ms-identity-java-daemon#8]
I'm using visual studio code in ubuntu 20.04 with openjdk 11, and followed the steps all the way to step 4.
Build successfully for the command below:
```bash
mvn clean compile assembly:single
```

I switched to `./target` directory before running the command before running it, where the jar was assembled the step above.  However, when running the jar, it fails with error below in terminal.

```bash
java -jar msal-client-credential-secret-1.0.0.jar
Exception in thread "main" java.lang.NullPointerException
        at ClientCredentialGrant.setUpSampleData(ClientCredentialGrant.java:99)
        at ClientCredentialGrant.main(ClientCredentialGrant.java:29)
```

Here is my java information below:
```bash
java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu120.04, mixed mode)
```

Here are the compiled results
```bash
find -ls
   786590      4 drwxrwxr-x   6 zyc      zyc          4096 Oct  7 18:47 .
   788005      4 drwxrwxr-x   3 zyc      zyc          4096 Oct  7 18:47 ./generated-sources
   788608      4 drwxrwxr-x   2 zyc      zyc          4096 Oct  7 18:47 ./generated-sources/annotations
   788609      4 drwxrwxr-x   3 zyc      zyc          4096 Oct  7 18:47 ./maven-status
   788610      4 drwxrwxr-x   3 zyc      zyc          4096 Oct  7 18:47 ./maven-status/maven-compiler-plugin
   788611      4 drwxrwxr-x   3 zyc      zyc          4096 Oct  7 18:47 ./maven-status/maven-compiler-plugin/compile
   788612      4 drwxrwxr-x   2 zyc      zyc          4096 Oct  7 18:47 ./maven-status/maven-compiler-plugin/compile/default-compile
   788614      4 -rw-rw-r--   1 zyc      zyc            28 Oct  7 18:47 ./maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst
   788615      4 -rw-rw-r--   1 zyc      zyc           127 Oct  7 18:47 ./maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
   788617   3740 -rw-rw-r--   1 zyc      zyc       3828487 Oct  7 18:47 ./msal-client-credential-secret-1.0.0.jar
   788616      4 drwxrwxr-x   2 zyc      zyc          4096 Oct  7 18:47 ./archive-tmp
   787157      4 drwxrwxr-x   2 zyc      zyc          4096 Oct  7 18:47 ./classes
   788613      8 -rw-rw-r--   1 zyc      zyc          6093 Oct  7 18:47 ./classes/ClientCredentialGrant.class
   787159      4 -rw-rw-r--   1 zyc      zyc           215 Oct  7 18:47 ./classes/application.properties
```

**Comment by Avery-Dunn** [comment]
Hello @penzyc : I was able to recreate your issue, and have a fix for it in https://github.com/Azure-Samples/ms-identity-java-daemon/pull/9. Basically, some changes were made to the sample to move the user configuration to a separate file, and I only tested the method to read that file directly in my IDE (IntelliJ/Windows/Java 1.8) and not after packaging the sample as a .jar

You can make the changes in https://github.com/Azure-Samples/ms-identity-java-daemon/pull/9 to your local copy of the sample (or pull the avdunn/path-fix branch and add your configuration), and you should be able to build/run it as a .jar just like you tried before. It's a pretty small fix (and you don't necessarily need the MSAL version updates I added to the sample's pom.xml), but I don't have an Ubuntu environment to easily test in so I'd like to confirm this change works in your environment.

**Comment by penzyc** [comment]
Hi @Avery-Dunn: Thanks for the quick fix.  I pulled and rebased your change.  I can confirm it's working for me.  Hopefully this can be merged soon.

**Comment by Avery-Dunn** [comment]
@penzyc : Glad to hear it! Just merged the changes (including your catch of that unneeded import).
